In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

X, y = make_classification(
    n_features=10, 
    n_samples=1000, 
    n_informative=8,
    n_redundant=2,
    n_repeated=0,
    n_classes=2, 
    random_state=42
)

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [2]:
from sklearn.metrics import classification_report

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.73      0.65      0.69       130
           1       0.66      0.74      0.70       120

    accuracy                           0.70       250
   macro avg       0.70      0.70      0.70       250
weighted avg       0.70      0.70      0.70       250



In [3]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=5,shuffle=True,random_state=42)

In [4]:
model=LogisticRegression()

from sklearn.model_selection import cross_val_score

cross_val_score(LogisticRegression(), X, y, cv=kf, scoring="accuracy")

array([0.675, 0.715, 0.72 , 0.645, 0.72 ])

In [8]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()

from sklearn.model_selection import cross_val_score

cross_val_score(DecisionTreeClassifier(), X, y, cv=kf, scoring="accuracy")

array([0.735, 0.815, 0.775, 0.83 , 0.815])

In [7]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()

from sklearn.model_selection import cross_val_score

cross_val_score(RandomForestClassifier(), X, y, cv=kf, scoring="accuracy")

array([0.865, 0.895, 0.905, 0.88 , 0.915])